### ISSUE TITLE
Admin Controllers Missing `$context` Object, no auth Populated

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#24] opened 2016-01-14 21:36 UTC
When the script split an admin controller into its main controllers and the base abstract controller, the main controller's constructor looked like this

    public function __construct(HelperData $helperData, 
        CfgporterData $cfgporterData, 
        LoggerInterface $logLoggerInterface, 
        LayoutFactory $viewLayoutFactory, 
        ScopeConfigInterface $configScopeConfigInterface, 
        Reader $dirReader)
    {

        parent::__construct($helperData, $cfgporterData, $logLoggerInterface, $viewLayoutFactory, $configScopeConfigInterface, $dirReader);
    }

And the base abstract controller looked like this

    public function __construct(\Package\Module\Helper\Data $helperData, 
        \Package\Module\Helper\Cfgporter\Data $cfgporterData, 
        \Psr\Log\LoggerInterface $logLoggerInterface, 
        \Magento\Framework\View\LayoutFactory $viewLayoutFactory, 
        \Magento\Framework\App\Config\ScopeConfigInterface $configScopeConfigInterface, 
        \Magento\Framework\Module\Dir\Reader $dirReader)
    {
        parent::__construct($context);
        $this->_helperData = $helperData;
        $this->_cfgporterData = $cfgporterData;
        $this->_logLoggerInterface = $logLoggerInterface;
        $this->_viewLayoutFactory = $viewLayoutFactory;
        $this->_configScopeConfigInterface = $configScopeConfigInterface;
        $this->_dirReader = $dirReader;

    }

This created two problems.  The first was the base abstract controller never called the parent controller's constructor method.  The second was the context object was left out of the main controller.  Both of these facts meant the following important method

    #File: vendor/magento/module-backend/App/AbstractAction.php
    public function __construct(Action\Context $context)
    {    
        parent::__construct($context);
        $this->_authorization = $context->getAuthorization();
        $this->_auth = $context->getAuth();
        $this->_helper = $context->getHelper();
        $this->_backendUrl = $context->getBackendUrl();
        $this->_formKeyValidator = $context->getFormKeyValidator();
        $this->_localeResolver = $context->getLocaleResolver();
        $this->_canUseBaseUrl = $context->getCanUseBaseUrl();
        $this->_session = $context->getSession();
    }

never got called, and the admin controller didn't have any of its helper objects, leading to errors like this

>     Fatal error: Call to a member function isLoggedIn() on null in /Users/alanstorm/Sites/magento-2-with-keys/magento2/vendor/magento/module-backend/App/AbstractAction.php on line 252

**Comment by unirgy** [comment] 2016-01-14 21:41
Hm... sorry can't reproduce, all my test controllers include `Context $context` and `parent::__construct($context)`

Is this problem in the same controller as in issue #21?

**Comment by astorm** [comment] 2016-01-14 21:42
@unirgy Yup, it is.  Probably related, eh?

**Comment by unirgy** [comment] 2016-01-14 21:42
Most likely. I'll do more testing with your code

**Comment by unirgy** [comment] 2016-01-14 22:58
Fixed #21, but dealing with some poltergeist in preg_match() for this one

**Comment by unirgy** [comment] 2016-01-14 23:05
Ok should be fixed

**Closed** 2016-01-18 23:40 UTC
